package water

var waterV2 = map[string]string{
	"watercreate":                "WaterCreate",
	"drawwater":                  "DrawWater",
	"setwaterposition":           "SetWaterPosition",
	"setwaterwavespeed":          "SetWaterWaveSpeed",
	"setwaterwaveheight":         "SetWaterWaveHeight",
	"setwaterwavefrequency":      "SetWaterWaveFrequency",
	"setwatertime":               "SetWaterTime",
	"watergetheight":             "WaterGetHeight",
	"setwatertexture":            "SetWaterTexture",
	"setwaterreflectiontexture":  "SetWaterReflectionTexture",
	"setwaterrefractiontexture":  "SetWaterRefractionTexture",
	"setwaternormalmap":          "SetWaterNormalMap",
	"setwatercolor":              "SetWaterColor",
	"setwatershininess":          "SetWaterShininess",
	"waterenablefoam":            "WaterEnableFoam",
	"watersetfoamintensity":      "WaterSetFoamIntensity",
	"watersetdepthfade":          "WaterSetDepthFade",
	"watersettransparency":       "WaterSetTransparency",
	"watersetdensity":            "WaterSetDensity",
	"watersetdrag":               "WaterSetDrag",
	"waterapplybuoyancy":         "WaterApplyBuoyancy",
	"setwaterscroll":             "SetWaterScroll",
	"setwaterreflection":         "SetWaterReflection",
	"setwaterrefraction":         "SetWaterRefraction",
	"setwaterdepthcolor":         "SetWaterDepthColor",
	"setwatershallowcolor":       "SetWaterShallowColor",
	"setwaterfoamtexture":        "SetWaterFoamTexture",
	"setwatervisible":            "SetWaterVisible",
}
