package std

// helpMap provides one-line help for HELP("command") / ?("command"). Kept in a separate file for easier editing.
var helpMap = map[string]string{
	"initwindow":        "InitWindow(width, height, title) – open game window",
	"closewindow":       "CloseWindow() – close window and exit",
	"settargetfps":      "SetTargetFPS(fps) – target frame rate",
	"getframetime":      "GetFrameTime() – delta time since last frame (seconds)",
	"windowshouldclose": "WindowShouldClose() – true when user requested close",
	"drawrectangle":     "DrawRectangle(x, y, w, h, r, g, b, a) – filled rectangle. Alias: rect(...)",
	"rect":              "rect(x, y, w, h, color...) – alias of DrawRectangle",
	"drawcircle":        "DrawCircle(x, y, radius, r, g, b, a) – filled circle. Alias: circle(...)",
	"circle":            "circle(x, y, radius, color...) – alias of DrawCircle",
	"drawtext":          "DrawText(text, x, y, size, r, g, b, a) – draw text",
	"drawtexture":       "DrawTexture(id, x, y [, tint]) – draw texture. Alias: sprite(...)",
	"sprite":            "sprite(id, x, y [, tint]) – alias of DrawTexture",
	"clearbackground":    "ClearBackground(r, g, b, a) – clear screen",
	"drawcube":          "DrawCube(x, y, z, w, h, d, color) – 3D cube. Alias: cube(...)",
	"cube":              "cube(x, y, z, w, h, d, color) – alias of DrawCube",
	"guibutton":         "GuiButton(x, y, w, h, text) – button; returns 1 if clicked. Alias: button(...)",
	"button":            "button(x, y, w, h, text) – alias of GuiButton",
	"keydown":           "KeyDown(key) – true while key held (e.g. KEY_W, KEY_ESCAPE)",
	"keypressed":        "KeyPressed(key) – true once when key pressed",
	"getmousex":         "GetMouseX() – mouse X",
	"getmousey":         "GetMouseY() – mouse Y",
	"createworld2d":     "CreateWorld2D(worldId, gx, gy) – create 2D physics world (flat API)",
	"step2d":            "Step2D(worldId, dt [, velIters, posIters]) – step 2D world",
	"createbox2d":       "CreateBox2D(worldId, bodyId, x, y, w, h, mass, isDynamic) – box body",
	"createbody2d":      "CreateBody2D(worldId, bodyId, type, shape, x, y, density, …) – body (type 0/1/2, shape 0=box 1=circle)",
	"getpositionx2d":   "GetPositionX2D(worldId, bodyId) – body X",
	"getpositiony2d":   "GetPositionY2D(worldId, bodyId) – body Y",
	"stepallphysics2d":  "StepAllPhysics2D(dt) – step all 2D worlds (called automatically in hybrid loop)",
	"createworld3d":     "CreateWorld3D(worldId, gx, gy, gz) – create 3D physics world (flat API)",
	"step3d":            "Step3D(worldId, dt) – step 3D world",
	"createbox3d":       "CreateBox3D(worldId, bodyId, x, y, z, hx, hy, hz, mass) – 3D box body",
	"createsphere3d":    "CreateSphere3D(worldId, bodyId, x, y, z, radius, mass) – 3D sphere",
	"getpositionx3d":   "GetPositionX3D(worldId, bodyId) – body X",
	"getpositiony3d":   "GetPositionY3D(worldId, bodyId) – body Y",
	"getpositionz3d":   "GetPositionZ3D(worldId, bodyId) – body Z",
	"stepallphysics3d":  "StepAllPhysics3D(dt) – step all 3D worlds (called automatically in hybrid loop)",
	"print":             "Print(value) – print to console",
	"str":               "Str(value) – convert to string",
	"int":               "Int(value) – convert to integer",
}
