package std

// stdV2 maps lowercase method names to RegisterForeign names (flat API unchanged).
var stdV2 = map[string]string{
	// Files / OS (overlap with filedot allowed)
	"readfile":        "ReadFile",
	"writefile":       "WriteFile",
	"loadtext":        "LoadText",
	"savetext":        "SaveText",
	"deletefile":      "DeleteFile",
	"copyfile":        "CopyFile",
	"listdir":         "ListDir",
	"dir":             "Dir",
	"directorylist":   "DirectoryList",
	"getdiritem":      "GetDirItem",
	"executefile":     "ExecuteFile",
	"getenv":          "GetEnv",
	"iswindowprocess": "IsWindowProcess",
	"getwindowtitle":  "GetWindowTitle",
	"getwindowwidth":  "GetWindowWidth",
	"getwindowheight": "GetWindowHeight",
	"spawnwindow":     "SpawnWindow",
	"help":            "HELP",
	// Strings / misc
	"left":       "Left",
	"right":      "Right",
	"mid":        "Mid",
	"substr":     "Substr",
	"upper":      "Upper",
	"lower":      "Lower",
	"len":        "Len",
	"instr":      "Instr",
	"chr":        "Chr",
	"asc":        "Asc",
	"str":        "Str",
	"val":        "Val",
	"waitkey":    "WaitKey",
	"printdebug": "PrintDebug",
	// Time / random
	"random":       "Random",
	"randomfloat":  "RandomFloat",
	"randomint":    "RandomInt",
	"rnd":          "Rnd",
	"timenow":      "TimeNow",
	"timerstart":   "TimerStart",
	"timerelapsed": "TimerElapsed",
	// Math
	"sin": "Sin", "cos": "Cos", "tan": "Tan", "sqrt": "Sqrt",
	"log": "Log", "int": "Int",
	"radians": "Radians", "degrees": "Degrees",
	"anglewrap": "AngleWrap", "wrapangle": "WrapAngle",
	// JSON / dict / save
	"loadjson":            "LoadJSON",
	"loadjsonfromstring":  "LoadJSONFromString",
	"getjsonkey":          "GetJSONKey",
	"createdict":          "CreateDict",
	"setdictkey":          "SetDictKey",
	"savejson":            "SaveJSON",
	"savegame":            "SaveGame",
	"loadgame":            "LoadGame",
	"autosave":            "Autosave",
	"saveexists":          "SaveExists",
	"loadlanguage":        "LoadLanguage",
	"setlanguage":         "SetLanguage",
	"translate":           "Translate",
	// HTTP
	"httpget":       "HttpGet",
	"httpgetasync":  "HttpGetAsync",
	"httpawait":     "HttpAwait",
	"httppost":      "HttpPost",
	"downloadfile": "DownloadFile",
	// Other
	"assert":      "Assert",
	"setloglevel": "SetLogLevel",
	"uuid":        "UUID",
	"isnull":      "IsNull",
	// Dictionary.* (single-segment method names)
	"dictionary_has":    "Dictionary.has",
	"dictionary_keys":   "Dictionary.keys",
	"dictionary_values": "Dictionary.values",
	"dictionary_size":   "Dictionary.size",
	"dictionary_remove": "Dictionary.remove",
	"dictionary_clear":  "Dictionary.clear",
	"dictionary_merge":  "Dictionary.merge",
	"dictionary_get":    "Dictionary.get",
	// Enum.*
	"enum_getvalue": "Enum.getValue",
	"enum_getname":  "Enum.getName",
	"enum_hasvalue": "Enum.hasValue",
}
