CREATEPHYSICSWORLD2D 0, -9.8
CREATEPHYSICSBODY2D "world", 1, 0, 2, 2, 1.0
SETPHYSICSPOSITION2D "body", 0, 5
STEPPHYSICS2D "world", 1.0/60.0, 8, 3
GETPHYSICSPOSITION2D "body"
DESTROYPHYSICSBODY2D "world", "body"
DESTROYPHYSICSWORLD2D "world"
PRINT "Box2D demo completed!"
