CREATEPHYSICSWORLD2D 0, -9.8
CREATEPHYSICSBODY2D "world", 1, 0, 2, 2, 1.0
SETPHYSICSPOSITION2D "box", 0, 5
STEPPHYSICS2D "world", 1.0/60.0, 8, 3
GETPHYSICSPOSITION2D "box"
DIM boxY AS FLOAT
DIM boxX AS FLOAT
boxY = POP()
boxX = POP()
PRINT boxX
PRINT boxY
APPLYPHYSICSFORCE2D "box", 10, 0, 0, 0
STEPPHYSICS2D "world", 1.0/60.0, 8, 3
GETPHYSICSPOSITION2D "box"
boxY = POP()
boxX = POP()
PRINT boxX
PRINT boxY
DESTROYPHYSICSBODY2D "world", "box"
DESTROYPHYSICSWORLD2D "world"
PRINT "Simplest Box2D demo completed!"
