package terrain

var terrainV2 = map[string]string{
	"loadheightmap":          "LoadHeightmap",
	"genheightmap":           "GenHeightmap",
	"genheightmapperlin":     "GenHeightmapPerlin",
	"genterrainmesh":         "GenTerrainMesh",
	"maketerrainflat":        "MakeTerrainFlat",
	"terraincreate":          "TerrainCreate",
	"terrainupdate":          "TerrainUpdate",
	"drawterrain":            "DrawTerrain",
	"setterraintexture":      "SetTerrainTexture",
	"setterrainmaterial":     "SetTerrainMaterial",
	"setterrainlod":          "SetTerrainLOD",
	"setterrainposition":     "SetTerrainPosition",
	"setterrainlayer":        "SetTerrainLayer",
	"setterrainsplatmap":     "SetTerrainSplatmap",
	"generateterrainnoise":   "GenerateTerrainNoise",
	"terrainraise":           "TerrainRaise",
	"terrainlower":           "TerrainLower",
	"terrainsmooth":          "TerrainSmooth",
	"terrainflatten":         "TerrainFlatten",
	"terrainpaint":           "TerrainPaint",
	"terraingetheight":       "TerrainGetHeight",
	"terraingetnormal":       "TerrainGetNormal",
	"terrainraycast":         "TerrainRaycast",
	"terrainenablecollision": "TerrainEnableCollision",
	"terrainsetfriction":     "TerrainSetFriction",
	"terrainsetbounce":       "TerrainSetBounce",
}
