package vegetation

var vegetationV2 = map[string]string{
	"treetypecreate":            "TreeTypeCreate",
	"treesystemcreate":          "TreeSystemCreate",
	"treeplace":                 "TreePlace",
	"treeremove":                "TreeRemove",
	"treesetposition":           "TreeSetPosition",
	"treesetscale":              "TreeSetScale",
	"treesetrotation":           "TreeSetRotation",
	"treesystemsetlod":          "TreeSystemSetLOD",
	"treesystemenableinstancing": "TreeSystemEnableInstancing",
	"treegetat":                 "TreeGetAt",
	"treeenablecollision":       "TreeEnableCollision",
	"treesetcollisionradius":    "TreeSetCollisionRadius",
	"treesetwind":               "TreeSetWind",
	"treeapplywind":             "TreeApplyWind",
	"treeraycast":               "TreeRaycast",
	"drawtrees":                 "DrawTrees",
	"grasscreate":               "GrassCreate",
	"grasssetwind":              "GrassSetWind",
	"grasssetheight":            "GrassSetHeight",
	"grasssetcolor":             "GrassSetColor",
	"grasspaint":                "GrassPaint",
	"grasserase":                "GrassErase",
	"grasssetdensity":           "GrassSetDensity",
	"grasssetlod":               "GrassSetLOD",
	"grassenableinstancing":     "GrassEnableInstancing",
	"grasssetbendamount":        "GrassSetBendAmount",
	"grasssetinteraction":       "GrassSetInteraction",
	"drawgrass":                 "DrawGrass",
}
